server:
  port: 9004

eureka:
  instance:
    name: balawo-rabbitmq
  client:
    register-with-eureka: true #表示将自己向注册中心注册 默认true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单点无所谓，集群必须设置为true才能配合使用ribbon使用负载均衡
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:9001/eureka/ #单机版

sys:
  config:
    rabbitmq:
      enabled: false
spring:
  application:
    name: balawo-rabbitmq

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #virtualHost: / #虚拟主机，默认是/
    virtualHost: springcloud2022
    listener:
      simple:
        acknowledge-mode: manual #手动签收
        prefetch: 1
    publisher-confirms: true #消息发送到交换机失败回调
    publisher-returns: true  #消息发送到队列失败回调
    template:
      mandatory: true # 必须设置成true 消息路由失败通知监听者，而不是将消息丢弃


