server:
  port: 9003

eureka:
  instance:
    name: balawo-oauth2-service
  client:
    register-with-eureka: true #表示将自己向注册中心注册 默认true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单点无所谓，集群必须设置为true才能配合使用ribbon使用负载均衡
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:9001/eureka/ #单机版


spring:
  application:
    name: balawo-oauth2
